name: Trigger Frontend Deployment

on:
  push:
    branches:
      - master

jobs:
  trigger_deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger deploy.yml in DevOps repo
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: Bearer ${{ secrets.DEVOPS_TOKEN }}" \
            https://api.github.com/repos/midoufkir/devops-ansible/dispatches \
            -d '{"event_type":"deploy_frontend"}'
